services:
  - type: web
    name: solar-nasih-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: solar-nasih-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0 