apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-multimodal-config
  namespace: rag-multimodal
data:
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  LOG_LEVEL: "INFO"
  DEBUG: "false"
  CHUNK_SIZE: "512"
  CHUNK_OVERLAP: "50"
  DEFAULT_TEXT_MODEL: "all-MiniLM-L6-v2"
  DEFAULT_IMAGE_MODEL: "clip-ViT-B-32"
  DEFAULT_LLM_MODEL: "gpt-3.5-turbo"
  VECTOR_COLLECTION_NAME: "multimodal_documents"
  VECTOR_SIZE: "384"
  QDRANT_URL: "http://qdrant-service:6333"
  REDIS_URL: "redis://redis-service:6379"
  DATABASE_URL: "postgresql://raguser:ragpassword@postgres-service:5432/rag_multimodal"